### ISSUE TITLE
Split individual actions into separate repos

### ISSUE THREAD

**Issue by helen** [10up/actions-wordpress#21]
It hurts me a little to do this, but since the GitHub Marketplace requires that Actions be in standalone repos and we don't actually share code between Actions here like I thought we might, it's time to split them before Actions goes into general release.

My plan for this repo is to leave it as-is as a table of contents/umbrella repo. I will also leave the action code as-is but update the readmes to point elsewhere. I am considering adding an info message to the actions to prompt people to move to using the new repos as well.

My plan for the new repos is to just start them with the existing code as first commit rather than jumping through hoops to retain what's really a minimally useful history. Since I'm going to leave this one alone, the history will still live on. I'll migrate issues, unclear if PRs can be migrated at the moment.

**Comment by jeffpaul** [comment]
@helen once the new repos are up an operating we might consider removing the action code from this umbrella repo lest someone continue to look to utilize it and miss out on enhancements happening in the correct/new repos.  Also since Actions are in beta, I think now would be the time to make these sorts of changes.
