### ISSUE TITLE
Need help to get actions to complete successfully

### ISSUE THREAD

**Issue by helgatheviking** [10up/actions-wordpress#30]
**Describe your question**

I know this is probably not meant to be a support forum, so my apologies for this, but I'm pretty stuck on getting these actions to run successfully. Today I was trying to update the readme for https://github.com/helgatheviking/KIA-Subtitle and the action fires, but ultimately fails. 

Here's the action log: https://github.com/helgatheviking/KIA-Subtitle/runs/599634112?check_suite_focus=true

and this is what seems to be the blocking issue:

```
ℹ︎ Using .distignore
rsync: change_dir "/github/workspace/.wordpress-org" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1207) [sender=3.1.3]
```

This plugin doesn't have a `.wordpress-org` folder as it has no assets. 
```

I tried updating the readme on another plugin 2 days ago and it also failed, though it looks like for a different reason. Here's the log: https://github.com/helgatheviking/Radio-Buttons-for-Taxonomies/runs/596530968?check_suite_focus=true

And here's where it gets stuck:
```
 ➤ Copying files...
ℹ︎ Using .distignore
➤ Preparing files...
!       trunk/LICENSE
?       trunk/composer.json
M       trunk/inc/class.Walker_Category_Radio.php
M       trunk/inc/class.Walker_Category_Radio_old.php
M       trunk/inc/class.WordPress_Radio_Taxonomy.php
M       trunk/inc/plugin-options.php
!       trunk/js/dist/index.asset.php
!       trunk/js/dist/index.deps.json
M       trunk/js/dist/index.js
!       trunk/js/dist/index.js.map
M       trunk/js/radiotax.js
M       trunk/js/src/index.js
M       trunk/js/src/radio-term-selector.js
M       trunk/js/src/terms.js
M       trunk/languages/radio-buttons-for-taxonomies-ar.po
M       trunk/languages/radio-buttons-for-taxonomies-de_DE.po
M       trunk/languages/radio-buttons-for-taxonomies-de_DE.pot
M       trunk/languages/radio-buttons-for-taxonomies-fa_IR.po
M       trunk/languages/radio-buttons-for-taxonomies-fr_FR.po
M       trunk/languages/radio-buttons-for-taxonomies-nl_NL.po
M       trunk/radio-buttons-for-taxonomies.php
M       trunk/readme.txt
M       trunk/webpack.config.js
🛑 Other files have been modified; changes not deployed
```

Which appears to be that some of the status of the other files have changed, but I'm not sure why that is impacting the action when I'm only trying to update the readme.txt file. (I'm also unclear on what additional parts of the webpack build process need to be in the .org repo, but that's not really related to your actions).

**Comment by helgatheviking** [comment]
Here's another failure from today: https://github.com/helgatheviking/KIA-Subtitle/runs/600068246?check_suite_focus=true

It appears to stop at `Set the GITHUB_TOKEN env variable` though I didn't think that environment variable was needed?

**Comment by Luc45** [comment]
Hi Helga,

I'm running the deploy script on a [plugin of mine](https://github.com/Luc45/WooCommerce-Correios-Calculo-de-Frete-na-Pagina-do-Produto/blob/master/.github/workflows/deploy-to-wordpress-repository.yml) without the `GITHUB_TOKEN` variable, so that shouldn't be needed. As for the other issue, try to remove this line from your `.distignore` file: `/.wordpress-org`

I believe that ignoring it might be causing it not to be available when the script tries to deploy that folder. I understand you don't want to share that folder with your theme/plugin, but if that works, you can then try to remove it without breaking the deploy.

**Comment by helen** [comment]
Hi @helgatheviking - sorry I didn't see this earlier. It looks like you need to update your references to use `10up/action-wordpress-plugin-deploy@master` in the workflow files - this specific repo you opened the issue in is now just an umbrella that links off to the individual Actions because GitHub requires them to be separate in order to show in their Marketplace.

**Comment by helen** [comment]
@helgatheviking Sorry, didn't quite finish typing. For the readme/asset updater, which you do have an updated reference for, it does require that no other changes be present after any other build steps because the Action itself doesn't really know whether the other changes in the meantime are functional and the preference is to be safe and not deploy early. The ability to specify paths in the workflow file cannot be set up to *only* include those files as far as I know from the last time I looked at this about a month ago, and since it's looking at the total contents of your repo and not the commit it's not reading into your intention. I'm interested in exploring ways to get smart about it, but haven't gotten there yet.

**Comment by helgatheviking** [comment]
Thank you both so much! I will give it a go and see what get. I might need to prune some of the SVN repo manually to remove some files that don't sent by this action... so the two sides "match".

@helen the ability to specify only those paths would help a lot.. too bad that's not possible.

**Comment by jeffpaul** [comment]
@helgatheviking are you all set up now or are there still additional questions we can help with?

**Comment by helgatheviking** [comment]
Hi @jeffpaul I can't really confirm anything since I haven't needed to update anything since. But I'll close this for now and come back to you if I get stuck again. Thank you both!
